# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: butakane-api
  namespace: butakane-dev
spec:
  type: NodePort
  selector:
    app: butakane-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081  # accessible from outside
