replicaCount: 1

image:
  repository: lysist/butakane-api
  tag: alpha-placeholder  # Will be overridden via --set or templated in Jenkins
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8081
  nodePort: 30081
  name: butakane-api-alpha

springProfile: alpha

namespace: butakane-dev

nameOverride: butakane-api-alpha